spring:
  application:
    name: hibernate-jsonb-poc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tutorial-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
server:
  port: 9090